/*
 * Copyright (c) 2026 L. Ledoux
 * SPDX-License-Identifier: Apache-2.0
 */

`default_nettype none

module tt_um_lledoux_bf16_diminished_kulisch (
    input  wire [7:0] ui_in,
    output logic [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
`ifdef USE_POWER_PINS
    ,
    inout  wire       VPWR,
    inout  wire       VGND
`endif
);

  localparam logic [1:0] ST_LOAD = 2'd0;
  localparam logic [1:0] ST_RUN  = 2'd1;
  localparam logic [1:0] ST_OUT  = 2'd2;

  localparam logic [4:0] FRAME_LAST = 5'd19;
  localparam logic [2:0] RUN_LATENCY_CYCLES = 3'd3;

  logic [1:0] state;
  logic [4:0] load_idx;
  logic [2:0] run_count;
  logic [1:0] out_idx;

  logic [31:0] a_words [0:1];
  logic [31:0] b_words [0:1];
  logic [31:0] c0_word;
  logic [31:0] result_word;

  logic [1:0][15:0] core_a;
  logic [1:0][15:0] core_b;
  logic [1:0][15:0] core_c;
  logic core_reset;
  logic [15:0] core_r;

  always @(*) begin
    core_a[0] = a_words[0][15:0];
    core_a[1] = a_words[1][15:0];
    core_b[0] = b_words[0][15:0];
    core_b[1] = b_words[1][15:0];
    core_c[0] = c0_word[15:0];
    core_c[1] = 16'h0000;
  end

  assign core_reset = (~rst_n) | (state == ST_LOAD);

  fpmult_loop_muladd_s3fdp s3fdp_core (
      .clk(clk),
      .reset(core_reset),
      .a(core_a),
      .b(core_b),
      .c(core_c),
      .clk_0(clk),
      .r(core_r)
  );

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= ST_LOAD;
      load_idx <= '0;
      run_count <= '0;
      out_idx <= '0;
      a_words[0] <= '0;
      a_words[1] <= '0;
      b_words[0] <= '0;
      b_words[1] <= '0;
      c0_word <= '0;
      result_word <= '0;
    end else if (ena) begin
      case (state)
        ST_LOAD: begin
          case (load_idx)
            5'd0:  a_words[0][7:0]   <= ui_in;
            5'd1:  a_words[0][15:8]  <= ui_in;
            5'd2:  a_words[0][23:16] <= ui_in;
            5'd3:  a_words[0][31:24] <= ui_in;
            5'd4:  a_words[1][7:0]   <= ui_in;
            5'd5:  a_words[1][15:8]  <= ui_in;
            5'd6:  a_words[1][23:16] <= ui_in;
            5'd7:  a_words[1][31:24] <= ui_in;
            5'd8:  b_words[0][7:0]   <= ui_in;
            5'd9:  b_words[0][15:8]  <= ui_in;
            5'd10: b_words[0][23:16] <= ui_in;
            5'd11: b_words[0][31:24] <= ui_in;
            5'd12: b_words[1][7:0]   <= ui_in;
            5'd13: b_words[1][15:8]  <= ui_in;
            5'd14: b_words[1][23:16] <= ui_in;
            5'd15: b_words[1][31:24] <= ui_in;
            5'd16: c0_word[7:0]      <= ui_in;
            5'd17: c0_word[15:8]     <= ui_in;
            5'd18: c0_word[23:16]    <= ui_in;
            5'd19: c0_word[31:24]    <= ui_in;
            default: ;
          endcase

          if (load_idx == FRAME_LAST) begin
            state <= ST_RUN;
            run_count <= '0;
          end else begin
            load_idx <= load_idx + 5'd1;
          end
        end

        ST_RUN: begin
          if (run_count == (RUN_LATENCY_CYCLES - 3'd1)) begin
            result_word <= {16'h0000, core_r};
            state <= ST_OUT;
            out_idx <= '0;
          end else begin
            run_count <= run_count + 3'd1;
          end
        end

        ST_OUT: begin
          if (out_idx == 2'd3) begin
            state <= ST_LOAD;
            load_idx <= '0;
            a_words[0] <= '0;
            a_words[1] <= '0;
            b_words[0] <= '0;
            b_words[1] <= '0;
            c0_word <= '0;
          end else begin
            out_idx <= out_idx + 2'd1;
          end
        end

        default: begin
          state <= ST_LOAD;
          load_idx <= '0;
          run_count <= '0;
          out_idx <= '0;
        end
      endcase
    end
  end

  always @(*) begin
    if (state == ST_OUT) begin
      case (out_idx)
        2'd0: uo_out = result_word[7:0];
        2'd1: uo_out = result_word[15:8];
        2'd2: uo_out = result_word[23:16];
        2'd3: uo_out = result_word[31:24];
        default: uo_out = 8'h00;
      endcase
    end else begin
      uo_out = 8'h00;
    end
  end

  assign uio_out = 8'h00;
  assign uio_oe  = 8'h00;

`ifdef USE_POWER_PINS
  wire _unused = &{uio_in, VPWR, VGND, 1'b0};
`else
  wire _unused = &{uio_in, 1'b0};
`endif

endmodule
// Generated by CIRCT 30ab7a85a
module fpmult_loop_muladd_s3fdp(
  input              clk,
                     reset,
  input  [1:0][15:0] a,
                     b,
                     c,
  input              clk_0,
  output [15:0]      r
);

  wire [31:0] _GEN;
  wire [31:0] _GEN_0;
  wire        _GEN_1;
  wire [15:0] _s3fdp_accum_r;
  wire [31:0] _GEN_2 = /*cast(bit[31:0])*/b;
  wire [31:0] _GEN_3 = /*cast(bit[31:0])*/a;
  reg  [15:0] c_mem[0:1];
  always_ff @(posedge clk_0) begin
    if (reset) begin
    end
    else begin
      if (_GEN_1)
        c_mem[1'h0] <= _s3fdp_accum_r;
    end
  end // always_ff @(posedge)
  reg  [31:0] _GEN_4;
  always_ff @(posedge clk_0) begin
    if (reset)
      _GEN_4 <= 32'h0;
    else
      _GEN_4 <= _GEN;
  end // always_ff @(posedge)
  assign _GEN_1 = _GEN_4 == 32'h0;
  reg  [31:0] _GEN_5;
  always_ff @(posedge clk_0) begin
    if (reset)
      _GEN_5 <= 32'h0;
    else
      _GEN_5 <= _GEN_0;
  end // always_ff @(posedge)
  wire        _GEN_6 = _GEN_5 == 32'h1;
  assign _GEN_0 = _GEN_1 ? (_GEN_6 ? 32'h0 : _GEN_5 + 32'h1) : _GEN_5;
  s3fdp_accum_core_wE8_wF7_cs16 s3fdp_accum (
    .clk   (clk),
    .reset (reset),
    .x     (_GEN_5[0] ? _GEN_3[31:16] : _GEN_3[15:0]),
    .y     (_GEN_5[0] ? _GEN_2[31:16] : _GEN_2[15:0]),
    .r     (_s3fdp_accum_r)
  );
  assign _GEN = _GEN_1 & _GEN_6 ? 32'h0 : _GEN_4;
  assign r = c_mem[1'h0];
endmodule

module s3fdp_accum_core_wE8_wF7_cs16(
  input         clk,
                reset,
  input  [15:0] x,
                y,
  output [15:0] r
);

  reg  [10:0]  _GEN;
  reg  [16:0]  _GEN_0;
  reg  [16:0]  _GEN_1;
  reg  [16:0]  _GEN_2;
  reg  [16:0]  _GEN_3;
  reg  [16:0]  _GEN_4;
  reg  [16:0]  _GEN_5;
  reg  [16:0]  _GEN_6;
  reg  [16:0]  _GEN_7;
  reg  [16:0]  _GEN_8;
  reg  [16:0]  _GEN_9;
  reg  [16:0]  _GEN_10;
  reg  [16:0]  _GEN_11;
  reg  [16:0]  _GEN_12;
  reg  [16:0]  _GEN_13;
  reg  [16:0]  _GEN_14;
  reg  [16:0]  _GEN_15;
  reg          _GEN_16;
  wire         _GEN_17 = x[14:7] == 8'h0;
  wire         _GEN_18 = y[14:7] == 8'h0;
  wire         _GEN_19 = x[15] ^ y[15];
  wire [15:0]  _GEN_20 =
    {16{_GEN_19}} ^ {8'h0, ~_GEN_17, x[6:0]} * {8'h0, ~_GEN_18, y[6:0]};
  wire [8:0]   _GEN_21 =
    {1'h0, _GEN_17 ? 8'h1 : x[14:7]} + {1'h0, _GEN_18 ? 8'h1 : y[14:7]} - 9'h78;
  wire [280:0] _GEN_22 = _GEN_21[8] ? {9'h0, _GEN_20, 256'h0} : {265'h0, _GEN_20};
  wire [280:0] _GEN_23 = _GEN_21[7] ? {_GEN_22[152:0], 128'h0} : _GEN_22;
  wire [280:0] _GEN_24 = _GEN_21[6] ? {_GEN_23[216:0], 64'h0} : _GEN_23;
  wire [280:0] _GEN_25 = _GEN_21[5] ? {_GEN_24[248:0], 32'h0} : _GEN_24;
  wire [280:0] _GEN_26 = _GEN_21[4] ? {_GEN_25[264:0], 16'h0} : _GEN_25;
  wire [272:0] _GEN_27 = _GEN_21[3] ? _GEN_26[272:0] : _GEN_26[280:8];
  wire [268:0] _GEN_28 = _GEN_21[2] ? _GEN_27[268:0] : _GEN_27[272:4];
  wire [266:0] _GEN_29 = _GEN_21[1] ? _GEN_28[266:0] : _GEN_28[268:2];
  wire [265:0] _GEN_30 =
    _GEN_21[8] ? 266'h0 : _GEN_21[0] ? _GEN_29[265:0] : _GEN_29[266:1];
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_16 <= 1'h0;
    else
      _GEN_16 <= (&(x[14:7])) | (&(y[14:7])) | _GEN_16;
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_15 <= 17'h0;
    else
      _GEN_15 <= {1'h0, _GEN_15[15:0]} + {1'h0, _GEN_30[15:0]} + {16'h0, _GEN_19};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_14 <= 17'h0;
    else
      _GEN_14 <= {1'h0, _GEN_14[15:0]} + {1'h0, _GEN_30[31:16]} + {16'h0, _GEN_15[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_13 <= 17'h0;
    else
      _GEN_13 <= {1'h0, _GEN_13[15:0]} + {1'h0, _GEN_30[47:32]} + {16'h0, _GEN_14[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_12 <= 17'h0;
    else
      _GEN_12 <= {1'h0, _GEN_12[15:0]} + {1'h0, _GEN_30[63:48]} + {16'h0, _GEN_13[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_11 <= 17'h0;
    else
      _GEN_11 <= {1'h0, _GEN_11[15:0]} + {1'h0, _GEN_30[79:64]} + {16'h0, _GEN_12[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_10 <= 17'h0;
    else
      _GEN_10 <= {1'h0, _GEN_10[15:0]} + {1'h0, _GEN_30[95:80]} + {16'h0, _GEN_11[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_9 <= 17'h0;
    else
      _GEN_9 <= {1'h0, _GEN_9[15:0]} + {1'h0, _GEN_30[111:96]} + {16'h0, _GEN_10[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_8 <= 17'h0;
    else
      _GEN_8 <= {1'h0, _GEN_8[15:0]} + {1'h0, _GEN_30[127:112]} + {16'h0, _GEN_9[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_7 <= 17'h0;
    else
      _GEN_7 <= {1'h0, _GEN_7[15:0]} + {1'h0, _GEN_30[143:128]} + {16'h0, _GEN_8[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_6 <= 17'h0;
    else
      _GEN_6 <= {1'h0, _GEN_6[15:0]} + {1'h0, _GEN_30[159:144]} + {16'h0, _GEN_7[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_5 <= 17'h0;
    else
      _GEN_5 <= {1'h0, _GEN_5[15:0]} + {1'h0, _GEN_30[175:160]} + {16'h0, _GEN_6[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_4 <= 17'h0;
    else
      _GEN_4 <= {1'h0, _GEN_4[15:0]} + {1'h0, _GEN_30[191:176]} + {16'h0, _GEN_5[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_3 <= 17'h0;
    else
      _GEN_3 <= {1'h0, _GEN_3[15:0]} + {1'h0, _GEN_30[207:192]} + {16'h0, _GEN_4[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_2 <= 17'h0;
    else
      _GEN_2 <= {1'h0, _GEN_2[15:0]} + {1'h0, _GEN_30[223:208]} + {16'h0, _GEN_3[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_1 <= 17'h0;
    else
      _GEN_1 <= {1'h0, _GEN_1[15:0]} + {1'h0, _GEN_30[239:224]} + {16'h0, _GEN_2[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_0 <= 17'h0;
    else
      _GEN_0 <= {1'h0, _GEN_0[15:0]} + {1'h0, _GEN_30[255:240]} + {16'h0, _GEN_1[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN <= 11'h0;
    else
      _GEN <= {1'h0, _GEN[9:0]} + {1'h0, _GEN_30[265:256]} + {10'h0, _GEN_0[16]};
  end // always_ff @(posedge)
  wire [265:0] _GEN_31 =
    {_GEN[9:0],
     _GEN_0[15:0],
     _GEN_1[15:0],
     _GEN_2[15:0],
     _GEN_3[15:0],
     _GEN_4[15:0],
     _GEN_5[15:0],
     _GEN_6[15:0],
     _GEN_7[15:0],
     _GEN_8[15:0],
     _GEN_9[15:0],
     _GEN_10[15:0],
     _GEN_11[15:0],
     _GEN_12[15:0],
     _GEN_13[15:0],
     _GEN_14[15:0],
     _GEN_15[15:0]}
    + {9'h0,
       _GEN_0[16],
       15'h0,
       _GEN_1[16],
       15'h0,
       _GEN_2[16],
       15'h0,
       _GEN_3[16],
       15'h0,
       _GEN_4[16],
       15'h0,
       _GEN_5[16],
       15'h0,
       _GEN_6[16],
       15'h0,
       _GEN_7[16],
       15'h0,
       _GEN_8[16],
       15'h0,
       _GEN_9[16],
       15'h0,
       _GEN_10[16],
       15'h0,
       _GEN_11[16],
       15'h0,
       _GEN_12[16],
       15'h0,
       _GEN_13[16],
       15'h0,
       _GEN_14[16],
       15'h0,
       _GEN_15[16],
       16'h0};
  wire         _GEN_32 = _GEN_31 == 266'h0;
  wire [265:0] _GEN_33 = _GEN_31[265] ? ~_GEN_31 + 266'h1 : _GEN_31;
  wire         _GEN_34 = _GEN_33[265:10] == 256'h0;
  wire [254:0] _GEN_35 = _GEN_34 ? {_GEN_33[9:0], 245'h0} : _GEN_33[265:11];
  wire         _GEN_36 = _GEN_35[254:127] == 128'h0;
  wire [126:0] _GEN_37 = _GEN_36 ? _GEN_35[126:0] : _GEN_35[254:128];
  wire         _GEN_38 = _GEN_37[126:63] == 64'h0;
  wire [62:0]  _GEN_39 = _GEN_38 ? _GEN_37[62:0] : _GEN_37[126:64];
  wire         _GEN_40 = _GEN_39[62:31] == 32'h0;
  wire [30:0]  _GEN_41 = _GEN_40 ? _GEN_39[30:0] : _GEN_39[62:32];
  wire         _GEN_42 = _GEN_41[30:15] == 16'h0;
  wire [14:0]  _GEN_43 = _GEN_42 ? _GEN_41[14:0] : _GEN_41[30:16];
  wire         _GEN_44 = _GEN_43[14:7] == 8'h0;
  wire [6:0]   _GEN_45 = _GEN_44 ? _GEN_43[6:0] : _GEN_43[14:8];
  wire         _GEN_46 = _GEN_45[6:3] == 4'h0;
  wire [2:0]   _GEN_47 = _GEN_46 ? _GEN_45[2:0] : _GEN_45[6:4];
  wire         _GEN_48 = _GEN_47[2:1] == 2'h0;
  wire         _GEN_49 = ~(_GEN_48 ? _GEN_47[0] : _GEN_47[2]);
  wire [264:0] _GEN_50 = _GEN_34 ? {_GEN_33[8:0], 256'h0} : _GEN_33[264:0];
  wire [264:0] _GEN_51 = _GEN_36 ? {_GEN_50[136:0], 128'h0} : _GEN_50;
  wire [264:0] _GEN_52 = _GEN_38 ? {_GEN_51[200:0], 64'h0} : _GEN_51;
  wire [264:0] _GEN_53 = _GEN_40 ? {_GEN_52[232:0], 32'h0} : _GEN_52;
  wire [264:0] _GEN_54 = _GEN_42 ? {_GEN_53[248:0], 16'h0} : _GEN_53;
  wire [264:0] _GEN_55 = _GEN_44 ? {_GEN_54[256:0], 8'h0} : _GEN_54;
  wire [264:0] _GEN_56 = _GEN_46 ? {_GEN_55[260:0], 4'h0} : _GEN_55;
  wire [264:0] _GEN_57 = _GEN_48 ? {_GEN_56[262:0], 2'h0} : _GEN_56;
  wire [264:0] _GEN_58 = _GEN_49 ? {_GEN_57[263:0], 1'h0} : _GEN_57;
  wire [8:0]   _GEN_59 =
    {2'h1, _GEN_58[264:258]}
    + {8'h0, _GEN_58[257] & (_GEN_58[256] | (|(_GEN_58[255:0])) | _GEN_58[258])};
  wire [10:0]  _GEN_60 =
    11'h84
    - {2'h0,
       _GEN_34,
       _GEN_36,
       _GEN_38,
       _GEN_40,
       _GEN_42,
       _GEN_44,
       _GEN_46,
       _GEN_48,
       _GEN_49} + {10'h0, _GEN_59[8]} + 11'h7F;
  wire         _GEN_61 = $signed(_GEN_60) < 11'sh1;
  wire         _GEN_62 = $signed(_GEN_60) > 11'shFE;
  assign r =
    _GEN_16
      ? 16'h7FC0
      : {_GEN_31[265],
         _GEN_62 ? 8'hFF : _GEN_61 | _GEN_32 ? 8'h0 : _GEN_60[7:0],
         _GEN_61 | _GEN_32 | _GEN_62 ? 7'h0 : _GEN_59[8] ? _GEN_59[7:1] : _GEN_59[6:0]};
endmodule

