/*
 * Copyright (c) 2026 L. Ledoux
 * SPDX-License-Identifier: Apache-2.0
 */

`default_nettype none

module tt_um_lledoux_s3fdp_seqcomb (
    input  wire [7:0] ui_in,
    output logic [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);

  localparam logic [1:0] ST_LOAD = 2'd0;
  localparam logic [1:0] ST_RUN  = 2'd1;
  localparam logic [1:0] ST_OUT  = 2'd2;

  localparam logic [4:0] FRAME_LAST = 5'd19;
  localparam logic [2:0] RUN_LATENCY_CYCLES = 3'd3;

  logic [1:0] state;
  logic [4:0] load_idx;
  logic [2:0] run_count;
  logic [1:0] out_idx;

  logic [31:0] a_words [0:1];
  logic [31:0] b_words [0:1];
  logic [31:0] c0_word;
  logic [31:0] result_word;

  logic [1:0][31:0] core_a;
  logic [1:0][31:0] core_b;
  logic [1:0][31:0] core_c;
  logic core_reset;
  logic [31:0] core_r;

  always @(*) begin
    core_a[0] = a_words[0];
    core_a[1] = a_words[1];
    core_b[0] = b_words[0];
    core_b[1] = b_words[1];
    core_c[0] = c0_word;
    core_c[1] = 32'h00000000;
  end

  assign core_reset = (~rst_n) | (state == ST_LOAD);

  fpmult_loop_muladd_s3fdp s3fdp_core (
      .clk(clk),
      .reset(core_reset),
      .a(core_a),
      .b(core_b),
      .c(core_c),
      .clk_0(clk),
      .r(core_r)
  );

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= ST_LOAD;
      load_idx <= '0;
      run_count <= '0;
      out_idx <= '0;
      a_words[0] <= '0;
      a_words[1] <= '0;
      b_words[0] <= '0;
      b_words[1] <= '0;
      c0_word <= '0;
      result_word <= '0;
    end else if (ena) begin
      case (state)
        ST_LOAD: begin
          case (load_idx)
            5'd0:  a_words[0][7:0]   <= ui_in;
            5'd1:  a_words[0][15:8]  <= ui_in;
            5'd2:  a_words[0][23:16] <= ui_in;
            5'd3:  a_words[0][31:24] <= ui_in;
            5'd4:  a_words[1][7:0]   <= ui_in;
            5'd5:  a_words[1][15:8]  <= ui_in;
            5'd6:  a_words[1][23:16] <= ui_in;
            5'd7:  a_words[1][31:24] <= ui_in;
            5'd8:  b_words[0][7:0]   <= ui_in;
            5'd9:  b_words[0][15:8]  <= ui_in;
            5'd10: b_words[0][23:16] <= ui_in;
            5'd11: b_words[0][31:24] <= ui_in;
            5'd12: b_words[1][7:0]   <= ui_in;
            5'd13: b_words[1][15:8]  <= ui_in;
            5'd14: b_words[1][23:16] <= ui_in;
            5'd15: b_words[1][31:24] <= ui_in;
            5'd16: c0_word[7:0]      <= ui_in;
            5'd17: c0_word[15:8]     <= ui_in;
            5'd18: c0_word[23:16]    <= ui_in;
            5'd19: c0_word[31:24]    <= ui_in;
            default: ;
          endcase

          if (load_idx == FRAME_LAST) begin
            state <= ST_RUN;
            run_count <= '0;
          end else begin
            load_idx <= load_idx + 5'd1;
          end
        end

        ST_RUN: begin
          if (run_count == (RUN_LATENCY_CYCLES - 3'd1)) begin
            result_word <= core_r;
            state <= ST_OUT;
            out_idx <= '0;
          end else begin
            run_count <= run_count + 3'd1;
          end
        end

        ST_OUT: begin
          if (out_idx == 2'd3) begin
            state <= ST_LOAD;
            load_idx <= '0;
            a_words[0] <= '0;
            a_words[1] <= '0;
            b_words[0] <= '0;
            b_words[1] <= '0;
            c0_word <= '0;
          end else begin
            out_idx <= out_idx + 2'd1;
          end
        end

        default: begin
          state <= ST_LOAD;
          load_idx <= '0;
          run_count <= '0;
          out_idx <= '0;
        end
      endcase
    end
  end

  always @(*) begin
    if (state == ST_OUT) begin
      case (out_idx)
        2'd0: uo_out = result_word[7:0];
        2'd1: uo_out = result_word[15:8];
        2'd2: uo_out = result_word[23:16];
        2'd3: uo_out = result_word[31:24];
        default: uo_out = 8'h00;
      endcase
    end else begin
      uo_out = 8'h00;
    end
  end

  assign uio_out = 8'h00;
  assign uio_oe  = 8'h00;

  wire _unused = &{uio_in, 1'b0};

endmodule
// Generated by CIRCT 30ab7a85a
module fpmult_loop_muladd_s3fdp(
  input              clk,
                     reset,
  input  [1:0][31:0] a,
                     b,
                     c,
  input              clk_0,
  output [31:0]      r
);

  wire [31:0] _GEN;
  wire [31:0] _GEN_0;
  wire        _GEN_1;
  wire [31:0] _s3fdp_accum_r;
  wire [63:0] _GEN_2 = /*cast(bit[63:0])*/b;
  wire [63:0] _GEN_3 = /*cast(bit[63:0])*/a;
  reg  [31:0] c_mem[0:1];
  always_ff @(posedge clk_0) begin
    if (reset) begin
    end
    else begin
      if (_GEN_1)
        c_mem[1'h0] <= _s3fdp_accum_r;
    end
  end // always_ff @(posedge)
  reg  [31:0] _GEN_4;
  always_ff @(posedge clk_0) begin
    if (reset)
      _GEN_4 <= 32'h0;
    else
      _GEN_4 <= _GEN;
  end // always_ff @(posedge)
  assign _GEN_1 = _GEN_4 == 32'h0;
  reg  [31:0] _GEN_5;
  always_ff @(posedge clk_0) begin
    if (reset)
      _GEN_5 <= 32'h0;
    else
      _GEN_5 <= _GEN_0;
  end // always_ff @(posedge)
  wire        _GEN_6 = _GEN_5 == 32'h1;
  assign _GEN_0 = _GEN_1 ? (_GEN_6 ? 32'h0 : _GEN_5 + 32'h1) : _GEN_5;
  s3fdp_accum_core_wE8_wF23_cs16 s3fdp_accum (
    .clk   (clk),
    .reset (reset),
    .x     (_GEN_5[0] ? _GEN_3[63:32] : _GEN_3[31:0]),
    .y     (_GEN_5[0] ? _GEN_2[63:32] : _GEN_2[31:0]),
    .r     (_s3fdp_accum_r)
  );
  assign _GEN = _GEN_1 & _GEN_6 ? 32'h0 : _GEN_4;
  assign r = c_mem[1'h0];
endmodule

module s3fdp_accum_core_wE8_wF23_cs16(
  input         clk,
                reset,
  input  [31:0] x,
                y,
  output [31:0] r
);

  reg  [13:0] _GEN;
  reg         _GEN_0;
  wire        _GEN_1 = x[30:23] == 8'h0;
  wire        _GEN_2 = y[30:23] == 8'h0;
  wire        _GEN_3 = x[31] ^ y[31];
  wire [8:0]  _GEN_4 =
    {1'h0, _GEN_1 ? 8'h1 : x[30:23]} + {1'h0, _GEN_2 ? 8'h1 : y[30:23]} - 9'hF7;
  wire [59:0] _GEN_5 =
    _GEN_4[6] | _GEN_4[7] | _GEN_4[8]
      ? 60'h0
      : {12'h0, {48{_GEN_3}} ^ {24'h0, ~_GEN_1, x[22:0]} * {24'h0, ~_GEN_2, y[22:0]}};
  wire [43:0] _GEN_6 = _GEN_4[5] ? {_GEN_5[27:0], 16'h0} : _GEN_5[59:16];
  wire [27:0] _GEN_7 = _GEN_4[4] ? _GEN_6[27:0] : _GEN_6[43:16];
  wire [19:0] _GEN_8 = _GEN_4[3] ? _GEN_7[19:0] : _GEN_7[27:8];
  wire [15:0] _GEN_9 = _GEN_4[2] ? _GEN_8[15:0] : _GEN_8[19:4];
  wire [13:0] _GEN_10 = _GEN_4[1] ? _GEN_9[13:0] : _GEN_9[15:2];
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_0 <= 1'h0;
    else
      _GEN_0 <= $signed(_GEN_4) > 9'shA | (&(x[30:23])) | (&(y[30:23])) | _GEN_0;
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN <= 14'h0;
    else
      _GEN <=
        {1'h0, _GEN[12:0]}
        + {1'h0, _GEN_4[8] ? 13'h0 : _GEN_4[0] ? _GEN_10[12:0] : _GEN_10[13:1]}
        + {13'h0, _GEN_3};
  end // always_ff @(posedge)
  wire        _GEN_11 = _GEN[12:0] == 13'h0;
  wire [12:0] _GEN_12 = _GEN[12] ? ~(_GEN[12:0]) + 13'h1 : _GEN[12:0];
  wire        _GEN_13 = _GEN_12[12:5] == 8'h0;
  wire [6:0]  _GEN_14 = _GEN_13 ? {_GEN_12[4:0], 2'h0} : _GEN_12[12:6];
  wire        _GEN_15 = _GEN_14[6:3] == 4'h0;
  wire [2:0]  _GEN_16 = _GEN_15 ? _GEN_14[2:0] : _GEN_14[6:4];
  wire        _GEN_17 = _GEN_16[2:1] == 2'h0;
  wire        _GEN_18 = ~(_GEN_17 ? _GEN_16[0] : _GEN_16[2]);
  wire [11:0] _GEN_19 = _GEN_13 ? {_GEN_12[3:0], 8'h0} : _GEN_12[11:0];
  wire [11:0] _GEN_20 = _GEN_15 ? {_GEN_19[7:0], 4'h0} : _GEN_19;
  wire [11:0] _GEN_21 = _GEN_17 ? {_GEN_20[9:0], 2'h0} : _GEN_20;
  wire [9:0]  _GEN_22 = 10'h6 - {6'h0, _GEN_13, _GEN_15, _GEN_17, _GEN_18} + 10'h7F;
  wire        _GEN_23 = $signed(_GEN_22) < 10'sh1;
  wire        _GEN_24 = $signed(_GEN_22) > 10'shFE;
  assign r =
    _GEN_0
      ? 32'h7FC00000
      : {_GEN[12],
         _GEN_24 ? 8'hFF : _GEN_23 | _GEN_11 ? 8'h0 : _GEN_22[7:0],
         _GEN_23 | _GEN_11 | _GEN_24
           ? 23'h0
           : {_GEN_18 ? {_GEN_21[10:0], 1'h0} : _GEN_21, 11'h0}};
endmodule

