/*
 * Copyright (c) 2026 L. Ledoux
 * SPDX-License-Identifier: Apache-2.0
 */

`default_nettype none

module tt_um_lledoux_s3fdp_seqcomb (
    input  wire [7:0] ui_in,
    output logic [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);

  localparam logic [1:0] ST_LOAD = 2'd0;
  localparam logic [1:0] ST_RUN  = 2'd1;
  localparam logic [1:0] ST_OUT  = 2'd2;

  localparam logic [4:0] FRAME_LAST = 5'd19;
  localparam logic [2:0] RUN_LATENCY_CYCLES = 3'd3;

  logic [1:0] state;
  logic [4:0] load_idx;
  logic [2:0] run_count;
  logic [1:0] out_idx;

  logic [31:0] a_words [0:1];
  logic [31:0] b_words [0:1];
  logic [31:0] c0_word;
  logic [31:0] result_word;

  logic [1:0][31:0] core_a;
  logic [1:0][31:0] core_b;
  logic [1:0][31:0] core_c;
  logic core_reset;
  logic [31:0] core_r;

  always @(*) begin
    core_a[0] = a_words[0];
    core_a[1] = a_words[1];
    core_b[0] = b_words[0];
    core_b[1] = b_words[1];
    core_c[0] = c0_word;
    core_c[1] = 32'h00000000;
  end

  assign core_reset = (~rst_n) | (state == ST_LOAD);

  fpmult_loop_muladd_s3fdp s3fdp_core (
      .clk(clk),
      .reset(core_reset),
      .a(core_a),
      .b(core_b),
      .c(core_c),
      .clk_0(clk),
      .r(core_r)
  );

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= ST_LOAD;
      load_idx <= '0;
      run_count <= '0;
      out_idx <= '0;
      a_words[0] <= '0;
      a_words[1] <= '0;
      b_words[0] <= '0;
      b_words[1] <= '0;
      c0_word <= '0;
      result_word <= '0;
    end else if (ena) begin
      case (state)
        ST_LOAD: begin
          case (load_idx)
            5'd0:  a_words[0][7:0]   <= ui_in;
            5'd1:  a_words[0][15:8]  <= ui_in;
            5'd2:  a_words[0][23:16] <= ui_in;
            5'd3:  a_words[0][31:24] <= ui_in;
            5'd4:  a_words[1][7:0]   <= ui_in;
            5'd5:  a_words[1][15:8]  <= ui_in;
            5'd6:  a_words[1][23:16] <= ui_in;
            5'd7:  a_words[1][31:24] <= ui_in;
            5'd8:  b_words[0][7:0]   <= ui_in;
            5'd9:  b_words[0][15:8]  <= ui_in;
            5'd10: b_words[0][23:16] <= ui_in;
            5'd11: b_words[0][31:24] <= ui_in;
            5'd12: b_words[1][7:0]   <= ui_in;
            5'd13: b_words[1][15:8]  <= ui_in;
            5'd14: b_words[1][23:16] <= ui_in;
            5'd15: b_words[1][31:24] <= ui_in;
            5'd16: c0_word[7:0]      <= ui_in;
            5'd17: c0_word[15:8]     <= ui_in;
            5'd18: c0_word[23:16]    <= ui_in;
            5'd19: c0_word[31:24]    <= ui_in;
            default: ;
          endcase

          if (load_idx == FRAME_LAST) begin
            state <= ST_RUN;
            run_count <= '0;
          end else begin
            load_idx <= load_idx + 5'd1;
          end
        end

        ST_RUN: begin
          if (run_count == (RUN_LATENCY_CYCLES - 3'd1)) begin
            result_word <= core_r;
            state <= ST_OUT;
            out_idx <= '0;
          end else begin
            run_count <= run_count + 3'd1;
          end
        end

        ST_OUT: begin
          if (out_idx == 2'd3) begin
            state <= ST_LOAD;
            load_idx <= '0;
            a_words[0] <= '0;
            a_words[1] <= '0;
            b_words[0] <= '0;
            b_words[1] <= '0;
            c0_word <= '0;
          end else begin
            out_idx <= out_idx + 2'd1;
          end
        end

        default: begin
          state <= ST_LOAD;
          load_idx <= '0;
          run_count <= '0;
          out_idx <= '0;
        end
      endcase
    end
  end

  always @(*) begin
    if (state == ST_OUT) begin
      case (out_idx)
        2'd0: uo_out = result_word[7:0];
        2'd1: uo_out = result_word[15:8];
        2'd2: uo_out = result_word[23:16];
        2'd3: uo_out = result_word[31:24];
        default: uo_out = 8'h00;
      endcase
    end else begin
      uo_out = 8'h00;
    end
  end

  assign uio_out = 8'h00;
  assign uio_oe  = 8'h00;

  wire _unused = &{uio_in, 1'b0};

endmodule
// Generated by CIRCT 30ab7a85a
module fpmult_loop_muladd_s3fdp(
  input              clk,
                     reset,
  input  [1:0][31:0] a,
                     b,
                     c,
  input              clk_0,
  output [31:0]      r
);

  wire [31:0] _GEN;
  wire [31:0] _GEN_0;
  wire        _GEN_1;
  wire [31:0] _s3fdp_accum_r;
  wire [63:0] _GEN_2 = /*cast(bit[63:0])*/b;
  wire [63:0] _GEN_3 = /*cast(bit[63:0])*/a;
  reg  [31:0] c_mem[0:1];
  always_ff @(posedge clk_0) begin
    if (reset) begin
    end
    else begin
      if (_GEN_1)
        c_mem[1'h0] <= _s3fdp_accum_r;
    end
  end // always_ff @(posedge)
  reg  [31:0] _GEN_4;
  always_ff @(posedge clk_0) begin
    if (reset)
      _GEN_4 <= 32'h0;
    else
      _GEN_4 <= _GEN;
  end // always_ff @(posedge)
  assign _GEN_1 = _GEN_4 == 32'h0;
  reg  [31:0] _GEN_5;
  always_ff @(posedge clk_0) begin
    if (reset)
      _GEN_5 <= 32'h0;
    else
      _GEN_5 <= _GEN_0;
  end // always_ff @(posedge)
  wire        _GEN_6 = _GEN_5 == 32'h1;
  assign _GEN_0 = _GEN_1 ? (_GEN_6 ? 32'h0 : _GEN_5 + 32'h1) : _GEN_5;
  s3fdp_accum_core_wE8_wF23_cs16 s3fdp_accum (
    .clk   (clk),
    .reset (reset),
    .x     (_GEN_5[0] ? _GEN_3[63:32] : _GEN_3[31:0]),
    .y     (_GEN_5[0] ? _GEN_2[63:32] : _GEN_2[31:0]),
    .r     (_s3fdp_accum_r)
  );
  assign _GEN = _GEN_1 & _GEN_6 ? 32'h0 : _GEN_4;
  assign r = c_mem[1'h0];
endmodule

module s3fdp_accum_core_wE8_wF23_cs16(
  input         clk,
                reset,
  input  [31:0] x,
                y,
  output [31:0] r
);

  reg  [13:0]  _GEN;
  reg  [16:0]  _GEN_0;
  reg  [16:0]  _GEN_1;
  reg  [16:0]  _GEN_2;
  reg  [16:0]  _GEN_3;
  reg  [16:0]  _GEN_4;
  reg  [16:0]  _GEN_5;
  reg  [16:0]  _GEN_6;
  reg  [16:0]  _GEN_7;
  reg  [16:0]  _GEN_8;
  reg  [16:0]  _GEN_9;
  reg  [16:0]  _GEN_10;
  reg  [16:0]  _GEN_11;
  reg  [16:0]  _GEN_12;
  reg  [16:0]  _GEN_13;
  reg  [16:0]  _GEN_14;
  reg  [16:0]  _GEN_15;
  reg  [16:0]  _GEN_16;
  reg  [16:0]  _GEN_17;
  reg  [16:0]  _GEN_18;
  reg  [16:0]  _GEN_19;
  reg  [16:0]  _GEN_20;
  reg  [16:0]  _GEN_21;
  reg  [16:0]  _GEN_22;
  reg  [16:0]  _GEN_23;
  reg  [16:0]  _GEN_24;
  reg  [16:0]  _GEN_25;
  reg  [16:0]  _GEN_26;
  reg  [16:0]  _GEN_27;
  reg  [16:0]  _GEN_28;
  reg  [16:0]  _GEN_29;
  reg  [16:0]  _GEN_30;
  reg  [16:0]  _GEN_31;
  reg  [16:0]  _GEN_32;
  reg  [16:0]  _GEN_33;
  reg          _GEN_34;
  wire         _GEN_35 = x[30:23] == 8'h0;
  wire         _GEN_36 = y[30:23] == 8'h0;
  wire         _GEN_37 = x[31] ^ y[31];
  wire [47:0]  _GEN_38 =
    {48{_GEN_37}} ^ {24'h0, ~_GEN_35, x[22:0]} * {24'h0, ~_GEN_36, y[22:0]};
  wire [8:0]   _GEN_39 =
    {1'h0, _GEN_35 ? 8'h1 : x[30:23]} + {1'h0, _GEN_36 ? 8'h1 : y[30:23]} + 9'h2D;
  wire [558:0] _GEN_40 = _GEN_39[8] ? {255'h0, _GEN_38, 256'h0} : {511'h0, _GEN_38};
  wire [558:0] _GEN_41 = _GEN_39[7] ? {_GEN_40[430:0], 128'h0} : _GEN_40;
  wire [558:0] _GEN_42 = _GEN_39[6] ? {_GEN_41[494:0], 64'h0} : _GEN_41;
  wire [542:0] _GEN_43 = _GEN_39[5] ? {_GEN_42[526:0], 16'h0} : _GEN_42[558:16];
  wire [526:0] _GEN_44 = _GEN_39[4] ? _GEN_43[526:0] : _GEN_43[542:16];
  wire [518:0] _GEN_45 = _GEN_39[3] ? _GEN_44[518:0] : _GEN_44[526:8];
  wire [514:0] _GEN_46 = _GEN_39[2] ? _GEN_45[514:0] : _GEN_45[518:4];
  wire [512:0] _GEN_47 = _GEN_39[1] ? _GEN_46[512:0] : _GEN_46[514:2];
  wire [556:0] _GEN_48 =
    _GEN_39[8] ? 557'h0 : {{45{_GEN_37}}, _GEN_39[0] ? _GEN_47[511:0] : _GEN_47[512:1]};
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_34 <= 1'h0;
    else
      _GEN_34 <= $signed(_GEN_39) > 9'sh28 | (&(x[30:23])) | (&(y[30:23])) | _GEN_34;
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_33 <= 17'h0;
    else
      _GEN_33 <= {1'h0, _GEN_33[15:0]} + {1'h0, _GEN_48[15:0]} + {16'h0, _GEN_37};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_32 <= 17'h0;
    else
      _GEN_32 <= {1'h0, _GEN_32[15:0]} + {1'h0, _GEN_48[31:16]} + {16'h0, _GEN_33[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_31 <= 17'h0;
    else
      _GEN_31 <= {1'h0, _GEN_31[15:0]} + {1'h0, _GEN_48[47:32]} + {16'h0, _GEN_32[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_30 <= 17'h0;
    else
      _GEN_30 <= {1'h0, _GEN_30[15:0]} + {1'h0, _GEN_48[63:48]} + {16'h0, _GEN_31[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_29 <= 17'h0;
    else
      _GEN_29 <= {1'h0, _GEN_29[15:0]} + {1'h0, _GEN_48[79:64]} + {16'h0, _GEN_30[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_28 <= 17'h0;
    else
      _GEN_28 <= {1'h0, _GEN_28[15:0]} + {1'h0, _GEN_48[95:80]} + {16'h0, _GEN_29[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_27 <= 17'h0;
    else
      _GEN_27 <= {1'h0, _GEN_27[15:0]} + {1'h0, _GEN_48[111:96]} + {16'h0, _GEN_28[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_26 <= 17'h0;
    else
      _GEN_26 <= {1'h0, _GEN_26[15:0]} + {1'h0, _GEN_48[127:112]} + {16'h0, _GEN_27[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_25 <= 17'h0;
    else
      _GEN_25 <= {1'h0, _GEN_25[15:0]} + {1'h0, _GEN_48[143:128]} + {16'h0, _GEN_26[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_24 <= 17'h0;
    else
      _GEN_24 <= {1'h0, _GEN_24[15:0]} + {1'h0, _GEN_48[159:144]} + {16'h0, _GEN_25[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_23 <= 17'h0;
    else
      _GEN_23 <= {1'h0, _GEN_23[15:0]} + {1'h0, _GEN_48[175:160]} + {16'h0, _GEN_24[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_22 <= 17'h0;
    else
      _GEN_22 <= {1'h0, _GEN_22[15:0]} + {1'h0, _GEN_48[191:176]} + {16'h0, _GEN_23[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_21 <= 17'h0;
    else
      _GEN_21 <= {1'h0, _GEN_21[15:0]} + {1'h0, _GEN_48[207:192]} + {16'h0, _GEN_22[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_20 <= 17'h0;
    else
      _GEN_20 <= {1'h0, _GEN_20[15:0]} + {1'h0, _GEN_48[223:208]} + {16'h0, _GEN_21[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_19 <= 17'h0;
    else
      _GEN_19 <= {1'h0, _GEN_19[15:0]} + {1'h0, _GEN_48[239:224]} + {16'h0, _GEN_20[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_18 <= 17'h0;
    else
      _GEN_18 <= {1'h0, _GEN_18[15:0]} + {1'h0, _GEN_48[255:240]} + {16'h0, _GEN_19[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_17 <= 17'h0;
    else
      _GEN_17 <= {1'h0, _GEN_17[15:0]} + {1'h0, _GEN_48[271:256]} + {16'h0, _GEN_18[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_16 <= 17'h0;
    else
      _GEN_16 <= {1'h0, _GEN_16[15:0]} + {1'h0, _GEN_48[287:272]} + {16'h0, _GEN_17[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_15 <= 17'h0;
    else
      _GEN_15 <= {1'h0, _GEN_15[15:0]} + {1'h0, _GEN_48[303:288]} + {16'h0, _GEN_16[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_14 <= 17'h0;
    else
      _GEN_14 <= {1'h0, _GEN_14[15:0]} + {1'h0, _GEN_48[319:304]} + {16'h0, _GEN_15[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_13 <= 17'h0;
    else
      _GEN_13 <= {1'h0, _GEN_13[15:0]} + {1'h0, _GEN_48[335:320]} + {16'h0, _GEN_14[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_12 <= 17'h0;
    else
      _GEN_12 <= {1'h0, _GEN_12[15:0]} + {1'h0, _GEN_48[351:336]} + {16'h0, _GEN_13[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_11 <= 17'h0;
    else
      _GEN_11 <= {1'h0, _GEN_11[15:0]} + {1'h0, _GEN_48[367:352]} + {16'h0, _GEN_12[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_10 <= 17'h0;
    else
      _GEN_10 <= {1'h0, _GEN_10[15:0]} + {1'h0, _GEN_48[383:368]} + {16'h0, _GEN_11[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_9 <= 17'h0;
    else
      _GEN_9 <= {1'h0, _GEN_9[15:0]} + {1'h0, _GEN_48[399:384]} + {16'h0, _GEN_10[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_8 <= 17'h0;
    else
      _GEN_8 <= {1'h0, _GEN_8[15:0]} + {1'h0, _GEN_48[415:400]} + {16'h0, _GEN_9[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_7 <= 17'h0;
    else
      _GEN_7 <= {1'h0, _GEN_7[15:0]} + {1'h0, _GEN_48[431:416]} + {16'h0, _GEN_8[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_6 <= 17'h0;
    else
      _GEN_6 <= {1'h0, _GEN_6[15:0]} + {1'h0, _GEN_48[447:432]} + {16'h0, _GEN_7[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_5 <= 17'h0;
    else
      _GEN_5 <= {1'h0, _GEN_5[15:0]} + {1'h0, _GEN_48[463:448]} + {16'h0, _GEN_6[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_4 <= 17'h0;
    else
      _GEN_4 <= {1'h0, _GEN_4[15:0]} + {1'h0, _GEN_48[479:464]} + {16'h0, _GEN_5[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_3 <= 17'h0;
    else
      _GEN_3 <= {1'h0, _GEN_3[15:0]} + {1'h0, _GEN_48[495:480]} + {16'h0, _GEN_4[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_2 <= 17'h0;
    else
      _GEN_2 <= {1'h0, _GEN_2[15:0]} + {1'h0, _GEN_48[511:496]} + {16'h0, _GEN_3[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_1 <= 17'h0;
    else
      _GEN_1 <= {1'h0, _GEN_1[15:0]} + {1'h0, _GEN_48[527:512]} + {16'h0, _GEN_2[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN_0 <= 17'h0;
    else
      _GEN_0 <= {1'h0, _GEN_0[15:0]} + {1'h0, _GEN_48[543:528]} + {16'h0, _GEN_1[16]};
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (reset)
      _GEN <= 14'h0;
    else
      _GEN <= {1'h0, _GEN[12:0]} + {1'h0, _GEN_48[556:544]} + {13'h0, _GEN_0[16]};
  end // always_ff @(posedge)
  wire [556:0] _GEN_49 =
    {_GEN[12:0],
     _GEN_0[15:0],
     _GEN_1[15:0],
     _GEN_2[15:0],
     _GEN_3[15:0],
     _GEN_4[15:0],
     _GEN_5[15:0],
     _GEN_6[15:0],
     _GEN_7[15:0],
     _GEN_8[15:0],
     _GEN_9[15:0],
     _GEN_10[15:0],
     _GEN_11[15:0],
     _GEN_12[15:0],
     _GEN_13[15:0],
     _GEN_14[15:0],
     _GEN_15[15:0],
     _GEN_16[15:0],
     _GEN_17[15:0],
     _GEN_18[15:0],
     _GEN_19[15:0],
     _GEN_20[15:0],
     _GEN_21[15:0],
     _GEN_22[15:0],
     _GEN_23[15:0],
     _GEN_24[15:0],
     _GEN_25[15:0],
     _GEN_26[15:0],
     _GEN_27[15:0],
     _GEN_28[15:0],
     _GEN_29[15:0],
     _GEN_30[15:0],
     _GEN_31[15:0],
     _GEN_32[15:0],
     _GEN_33[15:0]}
    + {12'h0,
       _GEN_0[16],
       15'h0,
       _GEN_1[16],
       15'h0,
       _GEN_2[16],
       15'h0,
       _GEN_3[16],
       15'h0,
       _GEN_4[16],
       15'h0,
       _GEN_5[16],
       15'h0,
       _GEN_6[16],
       15'h0,
       _GEN_7[16],
       15'h0,
       _GEN_8[16],
       15'h0,
       _GEN_9[16],
       15'h0,
       _GEN_10[16],
       15'h0,
       _GEN_11[16],
       15'h0,
       _GEN_12[16],
       15'h0,
       _GEN_13[16],
       15'h0,
       _GEN_14[16],
       15'h0,
       _GEN_15[16],
       15'h0,
       _GEN_16[16],
       15'h0,
       _GEN_17[16],
       15'h0,
       _GEN_18[16],
       15'h0,
       _GEN_19[16],
       15'h0,
       _GEN_20[16],
       15'h0,
       _GEN_21[16],
       15'h0,
       _GEN_22[16],
       15'h0,
       _GEN_23[16],
       15'h0,
       _GEN_24[16],
       15'h0,
       _GEN_25[16],
       15'h0,
       _GEN_26[16],
       15'h0,
       _GEN_27[16],
       15'h0,
       _GEN_28[16],
       15'h0,
       _GEN_29[16],
       15'h0,
       _GEN_30[16],
       15'h0,
       _GEN_31[16],
       15'h0,
       _GEN_32[16],
       15'h0,
       _GEN_33[16],
       16'h0};
  wire         _GEN_50 = _GEN_49 == 557'h0;
  wire [556:0] _GEN_51 = _GEN_49[556] ? ~_GEN_49 + 557'h1 : _GEN_49;
  wire         _GEN_52 = _GEN_51[556:45] == 512'h0;
  wire [510:0] _GEN_53 = _GEN_52 ? {_GEN_51[44:0], 466'h0} : _GEN_51[556:46];
  wire         _GEN_54 = _GEN_53[510:255] == 256'h0;
  wire [254:0] _GEN_55 = _GEN_54 ? _GEN_53[254:0] : _GEN_53[510:256];
  wire         _GEN_56 = _GEN_55[254:127] == 128'h0;
  wire [126:0] _GEN_57 = _GEN_56 ? _GEN_55[126:0] : _GEN_55[254:128];
  wire         _GEN_58 = _GEN_57[126:63] == 64'h0;
  wire [62:0]  _GEN_59 = _GEN_58 ? _GEN_57[62:0] : _GEN_57[126:64];
  wire         _GEN_60 = _GEN_59[62:31] == 32'h0;
  wire [30:0]  _GEN_61 = _GEN_60 ? _GEN_59[30:0] : _GEN_59[62:32];
  wire         _GEN_62 = _GEN_61[30:15] == 16'h0;
  wire [14:0]  _GEN_63 = _GEN_62 ? _GEN_61[14:0] : _GEN_61[30:16];
  wire         _GEN_64 = _GEN_63[14:7] == 8'h0;
  wire [6:0]   _GEN_65 = _GEN_64 ? _GEN_63[6:0] : _GEN_63[14:8];
  wire         _GEN_66 = _GEN_65[6:3] == 4'h0;
  wire [2:0]   _GEN_67 = _GEN_66 ? _GEN_65[2:0] : _GEN_65[6:4];
  wire         _GEN_68 = _GEN_67[2:1] == 2'h0;
  wire         _GEN_69 = ~(_GEN_68 ? _GEN_67[0] : _GEN_67[2]);
  wire [555:0] _GEN_70 = _GEN_52 ? {_GEN_51[43:0], 512'h0} : _GEN_51[555:0];
  wire [555:0] _GEN_71 = _GEN_54 ? {_GEN_70[299:0], 256'h0} : _GEN_70;
  wire [555:0] _GEN_72 = _GEN_56 ? {_GEN_71[427:0], 128'h0} : _GEN_71;
  wire [555:0] _GEN_73 = _GEN_58 ? {_GEN_72[491:0], 64'h0} : _GEN_72;
  wire [555:0] _GEN_74 = _GEN_60 ? {_GEN_73[523:0], 32'h0} : _GEN_73;
  wire [555:0] _GEN_75 = _GEN_62 ? {_GEN_74[539:0], 16'h0} : _GEN_74;
  wire [555:0] _GEN_76 = _GEN_64 ? {_GEN_75[547:0], 8'h0} : _GEN_75;
  wire [555:0] _GEN_77 = _GEN_66 ? {_GEN_76[551:0], 4'h0} : _GEN_76;
  wire [555:0] _GEN_78 = _GEN_68 ? {_GEN_77[553:0], 2'h0} : _GEN_77;
  wire [555:0] _GEN_79 = _GEN_69 ? {_GEN_78[554:0], 1'h0} : _GEN_78;
  wire [24:0]  _GEN_80 =
    {2'h1, _GEN_79[555:533]}
    + {24'h0, _GEN_79[532] & (_GEN_79[531] | (|(_GEN_79[530:0])) | _GEN_79[533])};
  wire [11:0]  _GEN_81 =
    12'h102
    - {2'h0,
       _GEN_52,
       _GEN_54,
       _GEN_56,
       _GEN_58,
       _GEN_60,
       _GEN_62,
       _GEN_64,
       _GEN_66,
       _GEN_68,
       _GEN_69} + {11'h0, _GEN_80[24]} + 12'h7F;
  wire         _GEN_82 = $signed(_GEN_81) < 12'sh1;
  wire         _GEN_83 = $signed(_GEN_81) > 12'shFE;
  assign r =
    _GEN_34
      ? 32'h7FC00000
      : {_GEN_49[556],
         _GEN_83 ? 8'hFF : _GEN_82 | _GEN_50 ? 8'h0 : _GEN_81[7:0],
         _GEN_82 | _GEN_50 | _GEN_83
           ? 23'h0
           : _GEN_80[24] ? _GEN_80[23:1] : _GEN_80[22:0]};
endmodule

